version: "3"
services:
  init-netplan:
    image: alpine
    command: sh -c "mkdir -p /etc/netplan && touch /etc/netplan/60-floating-ip.yaml"
    volumes:
      - netplan_data:/etc/netplan
    entrypoint: ["/bin/sh", "-c"]
    depends_on:
      - mariadb
    restart: "no"

  postal:
    image: ${POSTAL_IMAGE}
    depends_on:
      - init-netplan
      - mariadb
    entrypoint: ["/docker-entrypoint.sh"]
    volumes:
      - ./docker/ci-config:/config
      - netplan_data:/etc/netplan
    environment:
      POSTAL_SIGNING_KEY_PATH: /config/signing.key
      MAIN_DB_HOST: mariadb
      MAIN_DB_USERNAME: root
      MESSAGE_DB_HOST: mariadb
      MESSAGE_DB_USERNAME: root
      LOGGING_ENABLED: "false"
      RAILS_ENVIRONMENT: test
      RAILS_LOG_ENABLED: "false"
      WAIT_FOR_TIMEOUT: 90
      WAIT_FOR_TARGETS: |-
        mariadb:3306

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: postal
      MARIADB_ALLOW_EMPTY_PASSWORD: 'yes'
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'

volumes:
  netplan_data:
