web:
  host: postal.example.dev
  protocol: https

web_server:
  bind_address: 0.0.0.0
  port: 4010

smtp_server:
  port: 2525

logging:
  rails_log: true
  stdout: true

main_db:
  host: 127.0.0.1
  username: root
  password: 
  database: postal

message_db:
  host: 127.0.0.1
  username: root
  password: 
  prefix: postal

smtp:
  host: 127.0.0.1
  port: 2525
  username:
  password:
  from_name: Postal
  from_address: postal@yourdomain.com

rails:
  environment: development
  secret_key: 7f27856d26e864bafd49d0df37ad3d1339086e86ef0447e0f1814dde5277452fea97dab9e3aad6dfa11bfe359c82ce302d97bf1e58f6103c4408e4fbad4eeccf
